repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace

- repo: https://github.com/ambv/black
  rev: 22.10.0
  hooks:
  - id: black

- repo: local
  hooks:
  - id: prospector
    language: system
    types: [file, python]
    name: prospector
    description: "This hook runs Prospector: https://github.com/landscapeio/prospector"
    entry: prospector
