name: Continuous integration

on: [push, pull_request]

jobs:
  precommit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install python dependencies (prospector, etc.)
        run: |
          pip install -e .[dev]
          pip freeze

      - name: Run pre-commit
        run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

  dockertests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install python dependencies (pytest, etc.)
        run: |
          pip install -e .[dev]
          pip freeze

      - name: Start containers
        run: docker-compose -f "docker-compose-tests.yml" up -d --build

      - name: Wait for the service to be ready
        run: ./.ci/wait-for-it.sh localhost:8090 -t 120 && sleep 5

      - name: Run pytest
        run: pytest --driver Remote --capability browserName firefox .
